services:
  celery-beat:
    image: tvorchalavka/web-backend:develop
    restart: no
    volumes:
      - ../src:/src/
      - ../scripts:/scripts/

  celery-database-worker:
    image: tvorchalavka/web-backend:develop
    restart: no
    volumes:
      - ../src:/src/
      - ../scripts:/scripts/

  celery-elasticsearch-worker:
    image: tvorchalavka/web-backend:develop
    restart: no
    volumes:
      - ../src:/src/
      - ../scripts:/scripts/

  celery-notification-worker:
    image: tvorchalavka/web-backend:develop
    restart: no
    volumes:
      - ../src:/src/
      - ../scripts:/scripts/

  celery-statistics-worker:
    image: tvorchalavka/web-backend:develop
    restart: no
    volumes:
      - ../src:/src/
      - ../scripts:/scripts/
