# Generated by Django 5.1 on 2024-09-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.IntegerField(verbose_name="code")),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "email_type",
                    models.CharField(
                        choices=[("email_verification", "Email Verification"), ("reset_password", "Reset Password")],
                        max_length=20,
                        verbose_name="email type",
                    ),
                ),
                ("uuid", models.UUIDField(blank=True, null=True, verbose_name="uuid")),
            ],
            options={
                "verbose_name": "Verification Code",
                "verbose_name_plural": "Verification Codes",
                "db_table": "user_auth_verification_code",
            },
        ),
    ]
