# Generated by Django 5.1 on 2024-09-15 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.IntegerField()),
                (
                    "code_type",
                    models.CharField(
                        choices=[("email_verification", "Email Verification"), ("reset_password", "Reset Password")],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("uuid", models.UUIDField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Verification Code",
                "verbose_name_plural": "Verification Codes",
                "db_table": "user_auth_verification_code",
            },
        ),
    ]
