# Generated by Django 5.1 on 2024-12-06 12:01

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("avg_rating", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="UserReview",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("message", models.TextField(blank=True, max_length=500, null=True, verbose_name="message")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_reviews", to="review.review"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User review",
                "verbose_name_plural": "User reviews",
                "db_table": "review_userreview",
                "ordering": ["-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(fields=("content_type", "object_id"), name="unique_object_review"),
        ),
        migrations.AddConstraint(
            model_name="userreview",
            constraint=models.UniqueConstraint(fields=("user", "review"), name="unique_user_review"),
        ),
    ]
