repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: make eslint
        language: system
        types: [javascript, jsx]
        pass_filenames: false

      - id: prettier
        name: prettier
        entry: make prettier
        language: system
        types: [javascript, jsx]
        pass_filenames: false
