# ----- Dependencies ---------------------------------------------------------------------------------------------------
x-depends-on-redis: &x-depends-on-redis
  redis:
    condition: service_healthy

x-depends-on-backend: &x-depends-on-backend
  backend:
    condition: service_healthy

x-depends-on-rabbitmq: &x-depends-on-rabbitmq
  rabbitmq:
    condition: service_healthy


# ----- Services -------------------------------------------------------------------------------------------------------
services:

  # --- Redis ----------------------------------------------------------------------------------------------------------
  redis:
    extends:
      file: ./backend/docker-compose.yml
      service: redis


  # --- Backend --------------------------------------------------------------------------------------------------------
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    depends_on: *x-depends-on-redis


  # --- RabbitMQ -------------------------------------------------------------------------------------------------------
  rabbitmq:
    extends:
      file: ./backend/docker-compose.yml
      service: rabbitmq
    depends_on: *x-depends-on-backend


  # --- Celery ---------------------------------------------------------------------------------------------------------
  celery-worker-low-priority:
    extends:
      file: ./backend/docker-compose.yml
      service: celery-worker-low-priority
    depends_on: *x-depends-on-rabbitmq

  celery-worker-high-priority:
    extends:
      file: ./backend/docker-compose.yml
      service: celery-worker-high-priority
    depends_on: *x-depends-on-rabbitmq

  celery-beat:
    extends:
      file: ./backend/docker-compose.yml
      service: celery-beat
    depends_on: *x-depends-on-rabbitmq


  # --- Frontend -------------------------------------------------------------------------------------------------------
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    depends_on:
      - celery-worker-low-priority
      - celery-worker-high-priority


# ----- Volumes --------------------------------------------------------------------------------------------------------
volumes:
  rabbitmq_data:
  node_modules:
  redis_data:
  logs:
