# ----- Dependencies ---------------------------------------------------------------------------------------------------
x-depends-on-postgres-redis: &x-depends-on-postgres-redis
  postgres:
    condition: service_healthy
  redis:
    condition: service_healthy


# ----- Healthcheck ----------------------------------------------------------------------------------------------------
x-healthcheck: &x-healthcheck
  start_period: 30s
  interval: 30s
  timeout: 10s
  retries: 5

x-postgres-healthcheck: &x-postgres-healthcheck
  test: [ "CMD-SHELL", "pg_isready -U avnadmin -h postgres -p 5432" ]
  <<: *x-healthcheck

x-redis-healthcheck: &x-redis-healthcheck
  test: [ "CMD-SHELL", "redis-cli", "ping" ]
  <<: *x-healthcheck


# ----- Services -------------------------------------------------------------------------------------------------------
services:

  # --- Postgres -------------------------------------------------------------------------------------------------------
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: ../.env
    healthcheck: *x-postgres-healthcheck
    ports:
      - "5432:5432"

  # --- Redis ----------------------------------------------------------------------------------------------------------
  redis:
    image: redis:latest
    container_name: redis
    healthcheck: *x-redis-healthcheck
    ports:
      - "6379:6379"

  # --- Backend --------------------------------------------------------------------------------------------------------
  backend:
    image: marketplace-backend:latest
    container_name: backend
    env_file: ../.env
    environment:
      POSTGRES_HOST: postgres
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    user: root
    depends_on: *x-depends-on-postgres-redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/code/
