x-base-config: &x-base-config
  image: marketplace-backend:latest
  env_file: ../.env
  restart: always

services:
  celery-beat:
    <<: *x-base-config
    container_name: celery-beat
    command: celery -A core beat --loglevel=info
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/beat

  celery-worker-low-priority:
    <<: *x-base-config
    container_name: celery-worker-low-priority
    command: celery -A core worker --loglevel=info --autoscale=4,0 --max-tasks-per-child=10 --queues=low_priority
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/worker

  celery-worker-high-priority:
    <<: *x-base-config
    container_name: celery-worker-high-priority
    command: celery -A core worker --loglevel=info --autoscale=10,1 --max-tasks-per-child=50 --queues=high_priority
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/worker

  celery-database-worker:
    <<: *x-base-config
    container_name: celery-database-worker
    command: celery -A core worker --loglevel=info --autoscale=10,1 --max-tasks-per-child=50 --queues=database.queue
    volumes:
      - ./:/code/
      - logs:/var/log/backend/celery/worker
