import styles from './CatalogModal.module.css';
import { GoChevronRight } from 'react-icons/go';
import {useDispatch, useSelector} from 'react-redux'
import fotoAlternate from '../../images/not-found.png';
import { selectCategories } from '../../redux/categories/categoriesSelectors';
import { useEffect } from 'react';
import { getAllCategories } from '../../redux/categories/categoriesOperations';


export default function CatalogModal() {
    const categoryTree = [
      {
        id: 1,
        url: 'http://localhost:8080/ukrainian-craft',
        title: 'Українське ремесло',
        name: 'ukrainian-craft',
        description: '',
        order: 1,
        active: true,
        lft: 1,
        rght: 282,
        tree_id: 1,
        level: 0,
        parent: null,
        children: [
          {
            id: 2,
            url: 'http://localhost:8080/ukrainian-craft/pottery',
            title: 'Гончарство',
            name: 'pottery',
            description: '',
            order: 1,
            active: true,
            lft: 2,
            rght: 51,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 3,
                url: 'http://localhost:8080/ukrainian-craft/pottery/dishes',
                title: 'Посуд',
                name: 'dishes',
                description: '',
                order: 1,
                active: true,
                lft: 3,
                rght: 12,
                tree_id: 1,
                level: 2,
                parent: 2,
                children: [
                  {
                    id: 4,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/dishes/cups',
                    title: 'Чашки',
                    name: 'cups',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 4,
                    rght: 5,
                    tree_id: 1,
                    level: 3,
                    parent: 3,
                    children: [],
                  },
                  {
                    id: 5,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/dishes/plates',
                    title: 'Тарілки',
                    name: 'plates',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 6,
                    rght: 7,
                    tree_id: 1,
                    level: 3,
                    parent: 3,
                    children: [],
                  },
                  {
                    id: 6,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/dishes/kettles',
                    title: 'Чайники',
                    name: 'kettles',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 8,
                    rght: 9,
                    tree_id: 1,
                    level: 3,
                    parent: 3,
                    children: [],
                  },
                  {
                    id: 7,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/dishes/platters',
                    title: 'Блюда',
                    name: 'platters',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 10,
                    rght: 11,
                    tree_id: 1,
                    level: 3,
                    parent: 3,
                    children: [],
                  },
                ],
              },
              {
                id: 8,
                url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products',
                title: 'Декоративні вироби',
                name: 'decorative-products',
                description: '',
                order: 2,
                active: true,
                lft: 13,
                rght: 30,
                tree_id: 1,
                level: 2,
                parent: 2,
                children: [
                  {
                    id: 9,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/vases',
                    title: 'Вази',
                    name: 'vases',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 14,
                    rght: 15,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 10,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/sculptures',
                    title: 'Скульптури',
                    name: 'sculptures',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 16,
                    rght: 17,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 11,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/candlesticks',
                    title: 'Підсвічники',
                    name: 'candlesticks',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 18,
                    rght: 19,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 12,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/plates',
                    title: 'Декоративні тарілки',
                    name: 'plates',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 20,
                    rght: 21,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 13,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/panel',
                    title: 'Панно',
                    name: 'panel',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 22,
                    rght: 23,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 14,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/souvenirs',
                    title: 'Сувеніри',
                    name: 'souvenirs',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 24,
                    rght: 25,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 15,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/trivets',
                    title: 'Підставки під гаряче',
                    name: 'trivets',
                    description: '',
                    order: 7,
                    active: true,
                    lft: 26,
                    rght: 27,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                  {
                    id: 16,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/decorative-products/photo-frames',
                    title: 'Керамічні рамки для фото',
                    name: 'photo-frames',
                    description: '',
                    order: 8,
                    active: true,
                    lft: 28,
                    rght: 29,
                    tree_id: 1,
                    level: 3,
                    parent: 8,
                    children: [],
                  },
                ],
              },
              {
                id: 17,
                url: 'http://localhost:8080/ukrainian-craft/pottery/garden-ceramics',
                title: 'Садова кераміка',
                name: 'garden-ceramics',
                description: '',
                order: 3,
                active: true,
                lft: 31,
                rght: 36,
                tree_id: 1,
                level: 2,
                parent: 2,
                children: [
                  {
                    id: 18,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/garden-ceramics/pots',
                    title: 'Горщики для рослин',
                    name: 'pots',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 32,
                    rght: 33,
                    tree_id: 1,
                    level: 3,
                    parent: 17,
                    children: [],
                  },
                  {
                    id: 19,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/garden-ceramics/figures',
                    title: 'Садові фігури',
                    name: 'figures',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 34,
                    rght: 35,
                    tree_id: 1,
                    level: 3,
                    parent: 17,
                    children: [],
                  },
                ],
              },
              {
                id: 20,
                url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry',
                title: 'Прикраси',
                name: 'jewelry',
                description: '',
                order: 4,
                active: true,
                lft: 37,
                rght: 50,
                tree_id: 1,
                level: 2,
                parent: 2,
                children: [
                  {
                    id: 21,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/brooches',
                    title: 'Брошки',
                    name: 'brooches',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 38,
                    rght: 39,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                  {
                    id: 22,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/earrings',
                    title: 'Сережки',
                    name: 'earrings',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 40,
                    rght: 41,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                  {
                    id: 23,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/suspensions',
                    title: 'Підвіски',
                    name: 'suspensions',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 42,
                    rght: 43,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                  {
                    id: 24,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/pendants',
                    title: 'Кулони',
                    name: 'pendants',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 44,
                    rght: 45,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                  {
                    id: 25,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/bracelets',
                    title: 'Браслети',
                    name: 'bracelets',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 46,
                    rght: 47,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                  {
                    id: 26,
                    url: 'http://localhost:8080/ukrainian-craft/pottery/jewelry/rings',
                    title: 'Персні',
                    name: 'rings',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 48,
                    rght: 49,
                    tree_id: 1,
                    level: 3,
                    parent: 20,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 27,
            url: 'http://localhost:8080/ukrainian-craft/decorative-painting',
            title: 'Декоративний розпиc',
            name: 'decorative-painting',
            description: '',
            order: 2,
            active: true,
            lft: 52,
            rght: 121,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 28,
                url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes',
                title: 'Посуд',
                name: 'dishes',
                description: '',
                order: 1,
                active: true,
                lft: 53,
                rght: 64,
                tree_id: 1,
                level: 2,
                parent: 27,
                children: [
                  {
                    id: 29,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes/cups',
                    title: 'Чашки',
                    name: 'cups',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 54,
                    rght: 55,
                    tree_id: 1,
                    level: 3,
                    parent: 28,
                    children: [],
                  },
                  {
                    id: 30,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes/plates',
                    title: 'Тарілки',
                    name: 'plates',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 56,
                    rght: 57,
                    tree_id: 1,
                    level: 3,
                    parent: 28,
                    children: [],
                  },
                  {
                    id: 31,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes/kettles',
                    title: 'Чайники',
                    name: 'kettles',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 58,
                    rght: 59,
                    tree_id: 1,
                    level: 3,
                    parent: 28,
                    children: [],
                  },
                  {
                    id: 32,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes/platters',
                    title: 'Блюда',
                    name: 'platters',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 60,
                    rght: 61,
                    tree_id: 1,
                    level: 3,
                    parent: 28,
                    children: [],
                  },
                  {
                    id: 33,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/dishes/bowls',
                    title: 'Чаші та миски',
                    name: 'bowls',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 62,
                    rght: 63,
                    tree_id: 1,
                    level: 3,
                    parent: 28,
                    children: [],
                  },
                ],
              },
              {
                id: 34,
                url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes',
                title: 'Розписний одяг та аксесуари',
                name: 'clothes',
                description: '',
                order: 2,
                active: true,
                lft: 65,
                rght: 78,
                tree_id: 1,
                level: 2,
                parent: 27,
                children: [
                  {
                    id: 35,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/t-shirts',
                    title: 'Футболки',
                    name: 't-shirts',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 66,
                    rght: 67,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                  {
                    id: 36,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/jackets',
                    title: 'Куртки',
                    name: 'jackets',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 68,
                    rght: 69,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                  {
                    id: 37,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/dresses',
                    title: 'Сукні',
                    name: 'dresses',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 70,
                    rght: 71,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                  {
                    id: 38,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/jeans',
                    title: 'Джинси',
                    name: 'jeans',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 72,
                    rght: 73,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                  {
                    id: 39,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/bags',
                    title: 'Сумки',
                    name: 'bags',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 74,
                    rght: 75,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                  {
                    id: 40,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/clothes/shoes',
                    title: 'Взуття',
                    name: 'shoes',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 76,
                    rght: 77,
                    tree_id: 1,
                    level: 3,
                    parent: 34,
                    children: [],
                  },
                ],
              },
              {
                id: 41,
                url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry',
                title: 'Прикраси',
                name: 'jewelry',
                description: '',
                order: 3,
                active: true,
                lft: 79,
                rght: 92,
                tree_id: 1,
                level: 2,
                parent: 27,
                children: [
                  {
                    id: 42,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/brooches',
                    title: 'Брошки',
                    name: 'brooches',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 80,
                    rght: 81,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                  {
                    id: 43,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/earrings',
                    title: 'Сережки',
                    name: 'earrings',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 82,
                    rght: 83,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                  {
                    id: 44,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/suspensions',
                    title: 'Підвіски',
                    name: 'suspensions',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 84,
                    rght: 85,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                  {
                    id: 45,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/pendants',
                    title: 'Кулони',
                    name: 'pendants',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 86,
                    rght: 87,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                  {
                    id: 46,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/bracelets',
                    title: 'Браслети',
                    name: 'bracelets',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 88,
                    rght: 89,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                  {
                    id: 47,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/jewelry/rings',
                    title: 'Персні',
                    name: 'rings',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 90,
                    rght: 91,
                    tree_id: 1,
                    level: 3,
                    parent: 41,
                    children: [],
                  },
                ],
              },
              {
                id: 48,
                url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products',
                title: 'Декоративні вироби',
                name: 'products',
                description: '',
                order: 4,
                active: true,
                lft: 93,
                rght: 114,
                tree_id: 1,
                level: 2,
                parent: 27,
                children: [
                  {
                    id: 49,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/vases',
                    title: 'Вази',
                    name: 'vases',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 94,
                    rght: 95,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 50,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/sculptures',
                    title: 'Скульптури',
                    name: 'sculptures',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 96,
                    rght: 97,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 51,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/candlesticks',
                    title: 'Підсвічники',
                    name: 'candlesticks',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 98,
                    rght: 99,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 52,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/decor-plates',
                    title: 'Декоративні тарілки',
                    name: 'decor-plates',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 100,
                    rght: 101,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 53,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/decore-boards',
                    title: 'Декоративні дошки',
                    name: 'decore-boards',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 102,
                    rght: 103,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 54,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/trivets',
                    title: 'Підставки під гаряче',
                    name: 'trivets',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 104,
                    rght: 105,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 55,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/photo-frames',
                    title: 'Рамки для фото',
                    name: 'photo-frames',
                    description: '',
                    order: 7,
                    active: true,
                    lft: 106,
                    rght: 107,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 56,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/wall-clocks',
                    title: 'Настінні годинники',
                    name: 'wall-clocks',
                    description: '',
                    order: 8,
                    active: true,
                    lft: 108,
                    rght: 109,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 57,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/key-holders',
                    title: 'Ключниці',
                    name: 'key-holders',
                    description: '',
                    order: 9,
                    active: true,
                    lft: 110,
                    rght: 111,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                  {
                    id: 58,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/products/trays-and-stands',
                    title: 'Підноси та підставки',
                    name: 'trays-and-stands',
                    description: '',
                    order: 10,
                    active: true,
                    lft: 112,
                    rght: 113,
                    tree_id: 1,
                    level: 3,
                    parent: 48,
                    children: [],
                  },
                ],
              },
              {
                id: 59,
                url: 'http://localhost:8080/ukrainian-craft/decorative-painting/garden-decor',
                title: 'Садовий декор',
                name: 'garden-decor',
                description: '',
                order: 5,
                active: true,
                lft: 115,
                rght: 120,
                tree_id: 1,
                level: 2,
                parent: 27,
                children: [
                  {
                    id: 60,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/garden-decor/pots',
                    title: 'Горщики для рослин',
                    name: 'pots',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 116,
                    rght: 117,
                    tree_id: 1,
                    level: 3,
                    parent: 59,
                    children: [],
                  },
                  {
                    id: 61,
                    url: 'http://localhost:8080/ukrainian-craft/decorative-painting/garden-decor/figures',
                    title: 'Садові фігури',
                    name: 'figures',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 118,
                    rght: 119,
                    tree_id: 1,
                    level: 3,
                    parent: 59,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 62,
            url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making',
            title: 'Ткацтво і килимарство',
            name: 'weaving-and-carpet-making',
            description: '',
            order: 3,
            active: true,
            lft: 122,
            rght: 135,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 63,
                url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/scarves-and-handkerchiefs',
                title: 'Шарфи та хустки',
                name: 'scarves-and-handkerchiefs',
                description: '',
                order: 1,
                active: true,
                lft: 123,
                rght: 124,
                tree_id: 1,
                level: 2,
                parent: 62,
                children: [],
              },
              {
                id: 64,
                url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/decorative-textile-products',
                title: 'Декоративні текстильні вироби',
                name: 'decorative-textile-products',
                description: '',
                order: 2,
                active: true,
                lft: 125,
                rght: 134,
                tree_id: 1,
                level: 2,
                parent: 62,
                children: [
                  {
                    id: 65,
                    url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/decorative-textile-products/pillows',
                    title: 'Декоративні подушки',
                    name: 'pillows',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 126,
                    rght: 127,
                    tree_id: 1,
                    level: 3,
                    parent: 64,
                    children: [],
                  },
                  {
                    id: 66,
                    url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/decorative-textile-products/bedspreads-and-capes',
                    title: 'Покривала і накидки',
                    name: 'bedspreads-and-capes',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 128,
                    rght: 129,
                    tree_id: 1,
                    level: 3,
                    parent: 64,
                    children: [],
                  },
                  {
                    id: 67,
                    url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/decorative-textile-products/curtains-and-blinds',
                    title: 'Завіси та штори',
                    name: 'curtains-and-blinds',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 130,
                    rght: 131,
                    tree_id: 1,
                    level: 3,
                    parent: 64,
                    children: [],
                  },
                  {
                    id: 68,
                    url: 'http://localhost:8080/ukrainian-craft/weaving-and-carpet-making/decorative-textile-products/carpets-and-carpeting',
                    title: 'Килими та доріжки',
                    name: 'carpets-and-carpeting',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 132,
                    rght: 133,
                    tree_id: 1,
                    level: 3,
                    parent: 64,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 69,
            url: 'http://localhost:8080/ukrainian-craft/embroidery',
            title: 'Вишивка',
            name: 'embroidery',
            description: '',
            order: 4,
            active: true,
            lft: 136,
            rght: 185,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 70,
                url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing',
                title: 'Одяг',
                name: 'clothing',
                description: '',
                order: 1,
                active: true,
                lft: 137,
                rght: 164,
                tree_id: 1,
                level: 2,
                parent: 69,
                children: [
                  {
                    id: 71,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman',
                    title: 'Жіночий',
                    name: 'woman',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 138,
                    rght: 149,
                    tree_id: 1,
                    level: 3,
                    parent: 70,
                    children: [
                      {
                        id: 72,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman/embroidered-shirts',
                        title: 'Вишиванки',
                        name: 'embroidered-shirts',
                        description: '',
                        order: 1,
                        active: true,
                        lft: 139,
                        rght: 140,
                        tree_id: 1,
                        level: 4,
                        parent: 71,
                        children: [],
                      },
                      {
                        id: 73,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman/embroidered-pants',
                        title: 'Штанці',
                        name: 'embroidered-pants',
                        description: '',
                        order: 2,
                        active: true,
                        lft: 141,
                        rght: 142,
                        tree_id: 1,
                        level: 4,
                        parent: 71,
                        children: [],
                      },
                      {
                        id: 74,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman/embroidered-dresses',
                        title: 'Сукні',
                        name: 'embroidered-dresses',
                        description: '',
                        order: 3,
                        active: true,
                        lft: 143,
                        rght: 144,
                        tree_id: 1,
                        level: 4,
                        parent: 71,
                        children: [],
                      },
                      {
                        id: 75,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman/embroidered-blouses',
                        title: 'Блузки',
                        name: 'embroidered-blouses',
                        description: '',
                        order: 4,
                        active: true,
                        lft: 145,
                        rght: 146,
                        tree_id: 1,
                        level: 4,
                        parent: 71,
                        children: [],
                      },
                      {
                        id: 76,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/woman/embroidered-skirts',
                        title: 'Спідниці',
                        name: 'embroidered-skirts',
                        description: '',
                        order: 5,
                        active: true,
                        lft: 147,
                        rght: 148,
                        tree_id: 1,
                        level: 4,
                        parent: 71,
                        children: [],
                      },
                    ],
                  },
                  {
                    id: 77,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/man',
                    title: 'Чоловічий',
                    name: 'man',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 150,
                    rght: 153,
                    tree_id: 1,
                    level: 3,
                    parent: 70,
                    children: [
                      {
                        id: 78,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/man/embroidered-shirts',
                        title: 'Вишиванки',
                        name: 'embroidered-shirts',
                        description: '',
                        order: 1,
                        active: true,
                        lft: 151,
                        rght: 152,
                        tree_id: 1,
                        level: 4,
                        parent: 77,
                        children: [],
                      },
                    ],
                  },
                  {
                    id: 79,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/child',
                    title: 'Дитячий',
                    name: 'child',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 154,
                    rght: 163,
                    tree_id: 1,
                    level: 3,
                    parent: 70,
                    children: [
                      {
                        id: 80,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/child/embroidered-shirts-for-boys',
                        title: 'Вишиванка для хлопчиків',
                        name: 'embroidered-shirts-for-boys',
                        description: '',
                        order: 1,
                        active: true,
                        lft: 155,
                        rght: 156,
                        tree_id: 1,
                        level: 4,
                        parent: 79,
                        children: [],
                      },
                      {
                        id: 81,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/child/embroidered-shirts-for-girls',
                        title: 'Вишиванка для дівчаток',
                        name: 'embroidered-shirts-for-girls',
                        description: '',
                        order: 2,
                        active: true,
                        lft: 157,
                        rght: 158,
                        tree_id: 1,
                        level: 4,
                        parent: 79,
                        children: [],
                      },
                      {
                        id: 82,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/child/embroidered-dresses',
                        title: 'Дитячі сукні',
                        name: 'embroidered-dresses',
                        description: '',
                        order: 3,
                        active: true,
                        lft: 159,
                        rght: 160,
                        tree_id: 1,
                        level: 4,
                        parent: 79,
                        children: [],
                      },
                      {
                        id: 83,
                        url: 'http://localhost:8080/ukrainian-craft/embroidery/clothing/child/embroidered-pajamas',
                        title: 'Дитячі піжами',
                        name: 'embroidered-pajamas',
                        description: '',
                        order: 4,
                        active: true,
                        lft: 161,
                        rght: 162,
                        tree_id: 1,
                        level: 4,
                        parent: 79,
                        children: [],
                      },
                    ],
                  },
                ],
              },
              {
                id: 84,
                url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home',
                title: 'Текстиль для дому',
                name: 'textiles-for-home',
                description: '',
                order: 2,
                active: true,
                lft: 165,
                rght: 176,
                tree_id: 1,
                level: 2,
                parent: 69,
                children: [
                  {
                    id: 85,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home/towels',
                    title: 'Рушники',
                    name: 'towels',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 166,
                    rght: 167,
                    tree_id: 1,
                    level: 3,
                    parent: 84,
                    children: [],
                  },
                  {
                    id: 86,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home/tablecloths',
                    title: 'Скатертини',
                    name: 'tablecloths',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 168,
                    rght: 169,
                    tree_id: 1,
                    level: 3,
                    parent: 84,
                    children: [],
                  },
                  {
                    id: 87,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home/napkins-and-paths',
                    title: 'Серветки та доріжки',
                    name: 'napkins-and-paths',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 170,
                    rght: 171,
                    tree_id: 1,
                    level: 3,
                    parent: 84,
                    children: [],
                  },
                  {
                    id: 88,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home/decorative-pillows',
                    title: 'Декоративні подушки',
                    name: 'decorative-pillows',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 172,
                    rght: 173,
                    tree_id: 1,
                    level: 3,
                    parent: 84,
                    children: [],
                  },
                  {
                    id: 89,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/textiles-for-home/paintings-and-panels',
                    title: 'Картини та панно',
                    name: 'paintings-and-panels',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 174,
                    rght: 175,
                    tree_id: 1,
                    level: 3,
                    parent: 84,
                    children: [],
                  },
                ],
              },
              {
                id: 90,
                url: 'http://localhost:8080/ukrainian-craft/embroidery/accessories',
                title: 'Аксесуари',
                name: 'accessories',
                description: '',
                order: 3,
                active: true,
                lft: 177,
                rght: 184,
                tree_id: 1,
                level: 2,
                parent: 69,
                children: [
                  {
                    id: 91,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/accessories/bags',
                    title: 'Сумки',
                    name: 'bags',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 178,
                    rght: 179,
                    tree_id: 1,
                    level: 3,
                    parent: 90,
                    children: [],
                  },
                  {
                    id: 92,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/accessories/wallets',
                    title: 'Гаманці',
                    name: 'wallets',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 180,
                    rght: 181,
                    tree_id: 1,
                    level: 3,
                    parent: 90,
                    children: [],
                  },
                  {
                    id: 93,
                    url: 'http://localhost:8080/ukrainian-craft/embroidery/accessories/jewelry',
                    title: 'Прикраси (брошки, кулони, браслети)',
                    name: 'jewelry',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 182,
                    rght: 183,
                    tree_id: 1,
                    level: 3,
                    parent: 90,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 94,
            url: 'http://localhost:8080/ukrainian-craft/artistic-carving',
            title: 'Художнє різьблення',
            name: 'artistic-carving',
            description: '',
            order: 5,
            active: true,
            lft: 186,
            rght: 225,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 95,
                url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products',
                title: 'Декоративні вироби',
                name: 'decorative-products',
                description: '',
                order: 1,
                active: true,
                lft: 187,
                rght: 202,
                tree_id: 1,
                level: 2,
                parent: 94,
                children: [
                  {
                    id: 96,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/figurines-and-sculptures',
                    title: 'Фігурки та скульптури',
                    name: 'figurines-and-sculptures',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 188,
                    rght: 189,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 97,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/jewelry-boxes',
                    title: 'Шкатулки',
                    name: 'jewelry-boxes',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 190,
                    rght: 191,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 98,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/plates-and-dishes',
                    title: 'Тарілки та блюда',
                    name: 'plates-and-dishes',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 192,
                    rght: 193,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 99,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/frames-for-photos',
                    title: 'Рамки для фотографій',
                    name: 'frames-for-photos',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 194,
                    rght: 195,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 100,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/frames-for-mirrors',
                    title: 'Рами до дзеркал',
                    name: 'frames-for-mirrors',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 196,
                    rght: 197,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 101,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/key-holders',
                    title: 'Ключниці',
                    name: 'key-holders',
                    description: '',
                    order: 6,
                    active: true,
                    lft: 198,
                    rght: 199,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                  {
                    id: 102,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/decorative-products/phone-stands',
                    title: 'Підставки під телефон/техніку',
                    name: 'phone-stands',
                    description: '',
                    order: 7,
                    active: true,
                    lft: 200,
                    rght: 201,
                    tree_id: 1,
                    level: 3,
                    parent: 95,
                    children: [],
                  },
                ],
              },
              {
                id: 103,
                url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories',
                title: 'Прикраси та аксесуари',
                name: 'jewelry-and-accessories',
                description: '',
                order: 2,
                active: true,
                lft: 203,
                rght: 214,
                tree_id: 1,
                level: 2,
                parent: 94,
                children: [
                  {
                    id: 104,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories/pendants',
                    title: 'Кулони',
                    name: 'pendants',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 204,
                    rght: 205,
                    tree_id: 1,
                    level: 3,
                    parent: 103,
                    children: [],
                  },
                  {
                    id: 105,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories/bracelets',
                    title: 'Браслети',
                    name: 'bracelets',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 206,
                    rght: 207,
                    tree_id: 1,
                    level: 3,
                    parent: 103,
                    children: [],
                  },
                  {
                    id: 106,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories/brooches',
                    title: 'Брошки',
                    name: 'brooches',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 208,
                    rght: 209,
                    tree_id: 1,
                    level: 3,
                    parent: 103,
                    children: [],
                  },
                  {
                    id: 107,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories/combs-and-pins',
                    title: 'Гребінці та шпильки',
                    name: 'combs-and-pins',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 210,
                    rght: 211,
                    tree_id: 1,
                    level: 3,
                    parent: 103,
                    children: [],
                  },
                  {
                    id: 108,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/jewelry-and-accessories/keychains',
                    title: 'Брелоки',
                    name: 'keychains',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 212,
                    rght: 213,
                    tree_id: 1,
                    level: 3,
                    parent: 103,
                    children: [],
                  },
                ],
              },
              {
                id: 109,
                url: 'http://localhost:8080/ukrainian-craft/artistic-carving/kitchen-items',
                title: 'Предмети для кухні',
                name: 'kitchen-items',
                description: '',
                order: 3,
                active: true,
                lft: 215,
                rght: 224,
                tree_id: 1,
                level: 2,
                parent: 94,
                children: [
                  {
                    id: 110,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/kitchen-items/boards',
                    title: 'Дощечки',
                    name: 'boards',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 216,
                    rght: 217,
                    tree_id: 1,
                    level: 3,
                    parent: 109,
                    children: [],
                  },
                  {
                    id: 111,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/kitchen-items/spoons-and-forks',
                    title: 'Ложки та виделки',
                    name: 'spoons-and-forks',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 218,
                    rght: 219,
                    tree_id: 1,
                    level: 3,
                    parent: 109,
                    children: [],
                  },
                  {
                    id: 112,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/kitchen-items/dish-stands',
                    title: 'Підставки для посуду',
                    name: 'dish-stands',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 220,
                    rght: 221,
                    tree_id: 1,
                    level: 3,
                    parent: 109,
                    children: [],
                  },
                  {
                    id: 113,
                    url: 'http://localhost:8080/ukrainian-craft/artistic-carving/kitchen-items/napkin-holders-and-coasters',
                    title: 'Серветниці та підставки',
                    name: 'napkin-holders-and-coasters',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 222,
                    rght: 223,
                    tree_id: 1,
                    level: 3,
                    parent: 109,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 114,
            url: 'http://localhost:8080/ukrainian-craft/wickerwork',
            title: 'Лозоплетіння',
            name: 'wickerwork',
            description: '',
            order: 6,
            active: true,
            lft: 226,
            rght: 257,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 115,
                url: 'http://localhost:8080/ukrainian-craft/wickerwork/baskets',
                title: 'Кошики та корзинки',
                name: 'baskets',
                description: '',
                order: 1,
                active: true,
                lft: 227,
                rght: 236,
                tree_id: 1,
                level: 2,
                parent: 114,
                children: [
                  {
                    id: 116,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/baskets/storage-baskets',
                    title: 'Кошики для зберігання',
                    name: 'storage-baskets',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 228,
                    rght: 229,
                    tree_id: 1,
                    level: 3,
                    parent: 115,
                    children: [],
                  },
                  {
                    id: 117,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/baskets/picnic-baskets',
                    title: 'Кошики для пікніка',
                    name: 'picnic-baskets',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 230,
                    rght: 231,
                    tree_id: 1,
                    level: 3,
                    parent: 115,
                    children: [],
                  },
                  {
                    id: 118,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/baskets/laundry-baskets',
                    title: 'Кошики для білизни',
                    name: 'laundry-baskets',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 232,
                    rght: 233,
                    tree_id: 1,
                    level: 3,
                    parent: 115,
                    children: [],
                  },
                  {
                    id: 119,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/baskets/fruit-baskets',
                    title: 'Кошики для фруктів',
                    name: 'fruit-baskets',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 234,
                    rght: 235,
                    tree_id: 1,
                    level: 3,
                    parent: 115,
                    children: [],
                  },
                ],
              },
              {
                id: 120,
                url: 'http://localhost:8080/ukrainian-craft/wickerwork/decorative-items',
                title: 'Декоративні предмети',
                name: 'decorative-items',
                description: '',
                order: 2,
                active: true,
                lft: 237,
                rght: 244,
                tree_id: 1,
                level: 2,
                parent: 114,
                children: [
                  {
                    id: 121,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/decorative-items/wreaths',
                    title: 'Декоративні вінки',
                    name: 'wreaths',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 238,
                    rght: 239,
                    tree_id: 1,
                    level: 3,
                    parent: 120,
                    children: [],
                  },
                  {
                    id: 122,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/decorative-items/frames-for-photos',
                    title: 'Рамки для фотографій',
                    name: 'frames-for-photos',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 240,
                    rght: 241,
                    tree_id: 1,
                    level: 3,
                    parent: 120,
                    children: [],
                  },
                  {
                    id: 123,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/decorative-items/vine-candle-holders',
                    title: 'Лозові підсвічники',
                    name: 'vine-candle-holders',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 242,
                    rght: 243,
                    tree_id: 1,
                    level: 3,
                    parent: 120,
                    children: [],
                  },
                ],
              },
              {
                id: 124,
                url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories',
                title: 'Прикраси та аксесуари',
                name: 'jewelry-and-accessories',
                description: '',
                order: 3,
                active: true,
                lft: 245,
                rght: 256,
                tree_id: 1,
                level: 2,
                parent: 114,
                children: [
                  {
                    id: 125,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories/vine-bags',
                    title: 'Лозові сумки',
                    name: 'vine-bags',
                    description: '',
                    order: 1,
                    active: true,
                    lft: 246,
                    rght: 247,
                    tree_id: 1,
                    level: 3,
                    parent: 124,
                    children: [],
                  },
                  {
                    id: 126,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories/hats-and-headgear',
                    title: 'Капелюхи та головні убори',
                    name: 'hats-and-headgear',
                    description: '',
                    order: 2,
                    active: true,
                    lft: 248,
                    rght: 249,
                    tree_id: 1,
                    level: 3,
                    parent: 124,
                    children: [],
                  },
                  {
                    id: 127,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories/bracelets',
                    title: 'Браслети',
                    name: 'bracelets',
                    description: '',
                    order: 3,
                    active: true,
                    lft: 250,
                    rght: 251,
                    tree_id: 1,
                    level: 3,
                    parent: 124,
                    children: [],
                  },
                  {
                    id: 128,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories/necklaces',
                    title: 'Намиста',
                    name: 'necklaces',
                    description: '',
                    order: 4,
                    active: true,
                    lft: 252,
                    rght: 253,
                    tree_id: 1,
                    level: 3,
                    parent: 124,
                    children: [],
                  },
                  {
                    id: 129,
                    url: 'http://localhost:8080/ukrainian-craft/wickerwork/jewelry-and-accessories/pendants',
                    title: 'Кулони',
                    name: 'pendants',
                    description: '',
                    order: 5,
                    active: true,
                    lft: 254,
                    rght: 255,
                    tree_id: 1,
                    level: 3,
                    parent: 124,
                    children: [],
                  },
                ],
              },
            ],
          },
          {
            id: 130,
            url: 'http://localhost:8080/ukrainian-craft/blacksmithing',
            title: 'Ковальство',
            name: 'blacksmithing',
            description: '',
            order: 7,
            active: true,
            lft: 258,
            rght: 263,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 131,
                url: 'http://localhost:8080/ukrainian-craft/blacksmithing/sculptures',
                title: 'Скульптури',
                name: 'sculptures',
                description: '',
                order: 1,
                active: true,
                lft: 259,
                rght: 260,
                tree_id: 1,
                level: 2,
                parent: 130,
                children: [],
              },
              {
                id: 132,
                url: 'http://localhost:8080/ukrainian-craft/blacksmithing/decorative-products',
                title: 'Декоративні вироби',
                name: 'decorative-products',
                description: '',
                order: 2,
                active: true,
                lft: 261,
                rght: 262,
                tree_id: 1,
                level: 2,
                parent: 130,
                children: [],
              },
            ],
          },
          {
            id: 133,
            url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making',
            title: 'Виготовлення іграшок і оберегів',
            name: 'toy-and-amulet-making',
            description: '',
            order: 8,
            active: true,
            lft: 264,
            rght: 277,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [
              {
                id: 134,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/traditional-motanka-dolls',
                title: 'Традиційні ляльки-мотанки',
                name: 'traditional-motanka-dolls',
                description: '',
                order: 1,
                active: true,
                lft: 265,
                rght: 266,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
              {
                id: 135,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/knitted-amigurumi-toys',
                title: "В'язані іграшки (амігурумі)",
                name: 'knitted-amigurumi-toys',
                description: '',
                order: 2,
                active: true,
                lft: 267,
                rght: 268,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
              {
                id: 136,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/soft-toys',
                title: "М'які іграшки",
                name: 'soft-toys',
                description: '',
                order: 3,
                active: true,
                lft: 269,
                rght: 270,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
              {
                id: 137,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/wooden-toys',
                title: "Дерев'яні іграшки",
                name: 'wooden-toys',
                description: '',
                order: 4,
                active: true,
                lft: 271,
                rght: 272,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
              {
                id: 138,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/ceramic-amulets',
                title: 'Керамічні обереги',
                name: 'ceramic-amulets',
                description: '',
                order: 5,
                active: true,
                lft: 273,
                rght: 274,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
              {
                id: 139,
                url: 'http://localhost:8080/ukrainian-craft/toy-and-amulet-making/ritual-dolls-and-amulets',
                title: 'Обрядові ляльки та обереги',
                name: 'ritual-dolls-and-amulets',
                description: '',
                order: 6,
                active: true,
                lft: 275,
                rght: 276,
                tree_id: 1,
                level: 2,
                parent: 133,
                children: [],
              },
            ],
          },
          {
            id: 140,
            url: 'http://localhost:8080/ukrainian-craft/pysanky',
            title: 'Писанки',
            name: 'pysanky',
            description: '',
            order: 9,
            active: true,
            lft: 278,
            rght: 279,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [],
          },
          {
            id: 141,
            url: 'http://localhost:8080/ukrainian-craft/icon-painting',
            title: 'Іконопис',
            name: 'icon-painting',
            description: '',
            order: 10,
            active: true,
            lft: 280,
            rght: 281,
            tree_id: 1,
            level: 1,
            parent: 1,
            children: [],
          },
        ],
      },
    ];

    const categories = categoryTree.flatMap((cat) => cat.children);
    console.log(categories);
    const subcategories = categories.map((subCat) => subCat.children);
    console.log(subcategories);

    const dispatch = useDispatch();
    const categories1 = useSelector(selectCategories)
    console.log(categories1)
    useEffect(() => {
        dispatch(getAllCategories())
    }, [dispatch])
 return (
   <div className={styles.modal_box}>
     <div className={styles.box_categories}>
       <ul className={styles.list_categories}>
         {categories?.map(({ title, children }, index) => (
           <li key={index} className={styles.category_item}>
             <p className={styles.category}>{title}</p>
             {children.length > 0 && (
               <GoChevronRight className={styles.icon_right} />
             )}
           </li>
         ))}
       </ul>
     </div>
     <div className={styles.category_menu}>
       <div className={styles.scrollbox}>
         <div className={styles.scrollbox_inner}>
           <ul className={styles.list_cards}>
             <h2 className={styles.list_title}>{`${categories[0].title}`}</h2>
             {subcategories[0]?.map((item, index) => (
               <li key={index} className={styles.item_card}>
                 <img
                   src={item.url ? `${item.url}` : fotoAlternate}
                   alt=""
                   className={styles.item_img}
                 />
                 <div className={styles.box_text}>
                   <p className={styles.ttitle}>{item.title}</p>
                 </div>
               </li>
             ))}
           </ul>
         </div>
       </div>
     </div>
   </div>
 );
}
