# Generated by Django 5.1 on 2024-09-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="category_images/", verbose_name="image")),
                (
                    "title_position",
                    models.CharField(
                        choices=[
                            ("top-left", "top left"),
                            ("top-right", "top right"),
                            ("top-middle", "top middle"),
                            ("bottom-left", "bottom left"),
                            ("bottom-right", "bottom right"),
                            ("bottom-middle", "bottom middle"),
                        ],
                        default="top-left",
                        max_length=15,
                        verbose_name="title position",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image", to="category.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Image",
                "verbose_name_plural": "Category Images",
                "db_table": "category_image",
            },
        ),
    ]
