# Generated by Django 5.1 on 2024-11-10 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.category.utils


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "orientation",
                    models.CharField(
                        choices=[("vertical", "Vertical"), ("horizontal", "Horizontal")],
                        default="horizontal",
                        max_length=10,
                        verbose_name="orientation",
                    ),
                ),
                (
                    "title_position",
                    models.CharField(
                        choices=[
                            ("top-left", "Top left"),
                            ("top-right", "Top right"),
                            ("top-middle", "Top middle"),
                            ("bottom-left", "Bottom left"),
                            ("bottom-right", "Bottom right"),
                            ("bottom-middle", "Bottom middle"),
                        ],
                        default="top-left",
                        max_length=15,
                        verbose_name="title position",
                    ),
                ),
                ("text_wrap", models.BooleanField(default=True, verbose_name="text wrap")),
                (
                    "bg_color",
                    models.CharField(
                        max_length=7,
                        validators=[django.core.validators.MinLengthValidator(7)],
                        verbose_name="background color",
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "card design",
                "verbose_name_plural": "card designs",
                "db_table": "category_card",
            },
        ),
        migrations.CreateModel(
            name="CardImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.category.utils.category_card_images_upload_to, verbose_name="image"
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50, verbose_name="alt text")),
                ("size", models.FloatField(default=100, max_length=3, verbose_name="size")),
                ("x_axis", models.FloatField(default=0, verbose_name="x-axis")),
                ("y_axis", models.FloatField(default=0, verbose_name="y-axis")),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="category.card",
                        verbose_name="card",
                    ),
                ),
            ],
            options={
                "verbose_name": "category card image",
                "verbose_name_plural": "category card images",
                "db_table": "category_card_image",
            },
        ),
    ]
