# Generated by Django 5.1 on 2024-10-30 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryFilterSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_set",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "filters",
                    models.ManyToManyField(
                        related_name="category_filters", to="filter.filtergroupset", verbose_name="filters"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Filter Set",
                "verbose_name_plural": "Category Filter Sets",
                "db_table": "category_filter_set",
            },
        ),
    ]
