# Generated by Django 5.1 on 2024-09-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views_count", models.FloatField(default=0.0, verbose_name="views count")),
                ("purchases_count", models.FloatField(default=0.0, verbose_name="purchases count")),
                ("popularity_score", models.FloatField(default=0.0, verbose_name="popularity score")),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="category.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Statistic",
                "verbose_name_plural": "Category Statistics",
                "db_table": "category_statistic",
            },
        ),
    ]
