# Generated by Django 5.1 on 2024-10-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_filter_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views_count", models.FloatField(default=0.0, verbose_name="views count")),
                ("purchases_count", models.FloatField(default=0.0, verbose_name="purchases count")),
                ("popularity_score", models.FloatField(default=0.0, verbose_name="popularity score")),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category statistic",
                "verbose_name_plural": "category statistics",
                "db_table": "category_statistic",
            },
        ),
    ]
