# Generated by Django 5.2.3 on 2025-07-02 00:00

import django.db.models.deletion
import uuid6
from django.db import migrations, models

import apps.product.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("filter", "0001_initial"),
        ("user", "0002_seller_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        max_length=50, validators=[apps.product.validators.TitleValidator()], verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[apps.product.validators.DescriptionValidator()], verbose_name="description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.product.validators.PriceRangeValidator()],
                        verbose_name="price",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                (
                    "date_published",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="date published"),
                ),
                ("active", models.BooleanField(db_index=True, default=False, verbose_name="active")),
                ("draft", models.BooleanField(db_index=True, default=False, verbose_name="draft")),
                ("is_vip", models.BooleanField(db_index=True, default=False, verbose_name="vip")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "filters",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="filter.filtervalue", verbose_name="filters"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="user.sellerprofile",
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("hash", models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name="hash")),
                ("priority", models.PositiveSmallIntegerField(default=0, verbose_name="priority")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_image",
                "ordering": ["priority"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("priority__lte", 9)), name="priority_max_9")
                ],
            },
        ),
    ]
