# Generated by Django 5.0.7 on 2024-11-04 11:55

import apps.product.utils
import apps.product.validators
import django.db.models.deletion
import parler.fields
import parler.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0004_card"),
        ("filter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=100, verbose_name="slug")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.product.validators.PriceRangeValidator()],
                        verbose_name="price",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, validators=[apps.product.validators.ProductQuantity()], verbose_name="quantity"
                    ),
                ),
                (
                    "date_published",
                    models.DateField(blank=True, db_index=True, null=True, verbose_name="date published"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("is_vip", models.BooleanField(default=False, verbose_name="vip")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "filters",
                    models.ManyToManyField(
                        blank=True, related_name="product", to="filter.filtervalue", verbose_name="filters"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="seller",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to=apps.product.utils.product_image_path, verbose_name="image")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[apps.product.validators.ImagePriorityValidator()],
                        verbose_name="priority",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="product.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_image",
                "ordering": ("priority",),
            },
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Translation",
                "db_table": "product_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(fields=("product", "priority"), name="unique_product_image_priority"),
        ),
        migrations.AlterUniqueTogether(
            name="producttranslation",
            unique_together={("language_code", "master")},
        ),
    ]
