services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - tvorcha-network
    volumes:
      - redis_data:/data
    mem_limit: 256m
    cpus: 0.25

networks:
  tvorcha-network:
    external: true

volumes:
  redis_data: