services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file: ../../.env
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    networks:
      - tvorcha-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    mem_limit: 512m
    cpus: 0.25

networks:
  tvorcha-network:
    external: true

volumes:
  rabbitmq_data:
