# Generated by Django 5.1 on 2024-11-17 00:21

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0003_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "list_position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="list position",
                    ),
                ),
                ("required", models.BooleanField(default=False, verbose_name="required")),
            ],
            options={
                "verbose_name": "filter type",
                "verbose_name_plural": "filter types",
                "db_table": "filter_type",
                "ordering": ["list_position"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadata")),
                (
                    "filter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_values",
                        to="filter.filtertype",
                        verbose_name="filter type",
                    ),
                ),
            ],
            options={
                "verbose_name": "filter value",
                "verbose_name_plural": "filter values",
                "db_table": "filter_value",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FilterTypeTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="filter.filtertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "filter type Translation",
                "db_table": "filter_type_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FilterGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_groups",
                        to="category.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "filter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group",
                        to="filter.filtertype",
                        verbose_name="filter type",
                    ),
                ),
                (
                    "filter_values",
                    models.ManyToManyField(related_name="group", to="filter.filtervalue", verbose_name="filter values"),
                ),
            ],
            options={
                "verbose_name": "filter group",
                "verbose_name_plural": "filter groups",
                "db_table": "filter_group",
                "constraints": [
                    models.UniqueConstraint(fields=("filter_type", "category"), name="unique_filter_type_category")
                ],
            },
        ),
        migrations.CreateModel(
            name="FilterValueTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("value", models.CharField(max_length=50, verbose_name="value")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="filter.filtervalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "filter value Translation",
                "db_table": "filter_value_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
