# Generated by Django 5.1 on 2024-12-06 13:32

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.user.choices


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "public_username",
                    models.CharField(
                        max_length=150,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="public username",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("lite", "Lite"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("store", "Store"),
                        ],
                        default="free",
                        max_length=15,
                        verbose_name="plan",
                    ),
                ),
                (
                    "free_sales",
                    models.PositiveSmallIntegerField(
                        default=apps.user.choices.DefaultLimits.free_sales, verbose_name="free sales"
                    ),
                ),
                (
                    "vip_sales",
                    models.PositiveSmallIntegerField(
                        default=apps.user.choices.DefaultLimits.vip_sales, verbose_name="vip sales"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="seller_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "db_table": "user_seller_profile",
            },
        ),
    ]
