# Generated by Django 5.0.6 on 2024-08-03 13:51

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models

import apps.user.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, validators=[apps.user.validators.NameValidator()], verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, validators=[apps.user.validators.NameValidator()], verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                null=True,
                unique=True,
                validators=[apps.user.validators.PhoneNumberValidator()],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
