# Generated by Django 5.0.7 on 2024-08-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_is_email_verified"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
